# Generated by Django 3.0.5 on 2023-07-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udemycourse',
            name='search_query',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='search_query',
        ),
    ]
