# Generated by Django 3.0.5 on 2023-07-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20230706_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='udemycourse',
            name='search_query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='udemy_courses', to='sites.SearchQuery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='search_query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='sites.SearchQuery'),
            preserve_default=False,
        ),
    ]
