name: Deploy to Serveo

on:
  push:
    branches:
      - master

      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt 



      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa serveo.net >> ~/.ssh/known_hosts

      - name: Deploy to Serveo 
        run: |
          source .env
          ssh -o StrictHostKeyChecking=no -R $SERVEO_SUBDOMAIN:80:localhost:8000 serveo.net
